// Mocks generated by Mockito 5.4.6 from annotations
// in filed_notes/test/features/notes/data/repositories/notes_repository_impl_test.dart.
// Do not manually edit this file.

// ignore_for_file: no_leading_underscores_for_library_prefixes
import 'dart:async' as _i5;

import 'package:filed_notes/features/notes/data/datasources/notes_local_datasource.dart'
    as _i3;
import 'package:filed_notes/features/notes/data/datasources/notes_remote_datasource.dart'
    as _i6;
import 'package:filed_notes/features/notes/data/models/note_dto.dart' as _i2;
import 'package:filed_notes/features/notes/data/models/note_model.dart' as _i4;
import 'package:mockito/mockito.dart' as _i1;

// ignore_for_file: type=lint
// ignore_for_file: avoid_redundant_argument_values
// ignore_for_file: avoid_setters_without_getters
// ignore_for_file: comment_references
// ignore_for_file: deprecated_member_use
// ignore_for_file: deprecated_member_use_from_same_package
// ignore_for_file: implementation_imports
// ignore_for_file: invalid_use_of_visible_for_testing_member
// ignore_for_file: must_be_immutable
// ignore_for_file: prefer_const_constructors
// ignore_for_file: unnecessary_parenthesis
// ignore_for_file: camel_case_types
// ignore_for_file: subtype_of_sealed_class
// ignore_for_file: invalid_use_of_internal_member

class _FakeNoteDto_0 extends _i1.SmartFake implements _i2.NoteDto {
  _FakeNoteDto_0(
    Object parent,
    Invocation parentInvocation,
  ) : super(
          parent,
          parentInvocation,
        );
}

/// A class which mocks [NotesLocalDatasource].
///
/// See the documentation for Mockito's code generation for more information.
class MockNotesLocalDatasource extends _i1.Mock
    implements _i3.NotesLocalDatasource {
  MockNotesLocalDatasource() {
    _i1.throwOnMissingStub(this);
  }

  @override
  List<_i4.NoteModel> getAll() => (super.noSuchMethod(
        Invocation.method(
          #getAll,
          [],
        ),
        returnValue: <_i4.NoteModel>[],
      ) as List<_i4.NoteModel>);

  @override
  _i4.NoteModel? getById(String? id) => (super.noSuchMethod(Invocation.method(
        #getById,
        [id],
      )) as _i4.NoteModel?);

  @override
  _i5.Future<void> put(_i4.NoteModel? model) => (super.noSuchMethod(
        Invocation.method(
          #put,
          [model],
        ),
        returnValue: _i5.Future<void>.value(),
        returnValueForMissingStub: _i5.Future<void>.value(),
      ) as _i5.Future<void>);

  @override
  _i5.Future<void> delete(String? id) => (super.noSuchMethod(
        Invocation.method(
          #delete,
          [id],
        ),
        returnValue: _i5.Future<void>.value(),
        returnValueForMissingStub: _i5.Future<void>.value(),
      ) as _i5.Future<void>);

  @override
  _i5.Future<void> putAll(Iterable<_i4.NoteModel>? models) =>
      (super.noSuchMethod(
        Invocation.method(
          #putAll,
          [models],
        ),
        returnValue: _i5.Future<void>.value(),
        returnValueForMissingStub: _i5.Future<void>.value(),
      ) as _i5.Future<void>);
}

/// A class which mocks [NotesRemoteDatasource].
///
/// See the documentation for Mockito's code generation for more information.
class MockNotesRemoteDatasource extends _i1.Mock
    implements _i6.NotesRemoteDatasource {
  MockNotesRemoteDatasource() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i5.Future<List<_i2.NoteDto>> getNotes() => (super.noSuchMethod(
        Invocation.method(
          #getNotes,
          [],
        ),
        returnValue: _i5.Future<List<_i2.NoteDto>>.value(<_i2.NoteDto>[]),
      ) as _i5.Future<List<_i2.NoteDto>>);

  @override
  _i5.Future<_i2.NoteDto> getNoteById(String? id) => (super.noSuchMethod(
        Invocation.method(
          #getNoteById,
          [id],
        ),
        returnValue: _i5.Future<_i2.NoteDto>.value(_FakeNoteDto_0(
          this,
          Invocation.method(
            #getNoteById,
            [id],
          ),
        )),
      ) as _i5.Future<_i2.NoteDto>);

  @override
  _i5.Future<_i2.NoteDto> createNote(_i2.NoteDto? noteDto) =>
      (super.noSuchMethod(
        Invocation.method(
          #createNote,
          [noteDto],
        ),
        returnValue: _i5.Future<_i2.NoteDto>.value(_FakeNoteDto_0(
          this,
          Invocation.method(
            #createNote,
            [noteDto],
          ),
        )),
      ) as _i5.Future<_i2.NoteDto>);

  @override
  _i5.Future<_i2.NoteDto> updateNote(_i2.NoteDto? noteDto) =>
      (super.noSuchMethod(
        Invocation.method(
          #updateNote,
          [noteDto],
        ),
        returnValue: _i5.Future<_i2.NoteDto>.value(_FakeNoteDto_0(
          this,
          Invocation.method(
            #updateNote,
            [noteDto],
          ),
        )),
      ) as _i5.Future<_i2.NoteDto>);

  @override
  _i5.Future<void> deleteNote(String? id) => (super.noSuchMethod(
        Invocation.method(
          #deleteNote,
          [id],
        ),
        returnValue: _i5.Future<void>.value(),
        returnValueForMissingStub: _i5.Future<void>.value(),
      ) as _i5.Future<void>);

  @override
  void dispose() => super.noSuchMethod(
        Invocation.method(
          #dispose,
          [],
        ),
        returnValueForMissingStub: null,
      );
}
