// Mocks generated by Mockito 5.4.6 from annotations
// in filed_notes/test/features/notes/presentation/providers/notes_providers_test.dart.
// Do not manually edit this file.

// ignore_for_file: no_leading_underscores_for_library_prefixes
import 'dart:async' as _i4;

import 'package:filed_notes/features/notes/domain/entities/note.dart' as _i2;
import 'package:filed_notes/features/notes/domain/repositories/notes_repository.dart'
    as _i3;
import 'package:mockito/mockito.dart' as _i1;

// ignore_for_file: type=lint
// ignore_for_file: avoid_redundant_argument_values
// ignore_for_file: avoid_setters_without_getters
// ignore_for_file: comment_references
// ignore_for_file: deprecated_member_use
// ignore_for_file: deprecated_member_use_from_same_package
// ignore_for_file: implementation_imports
// ignore_for_file: invalid_use_of_visible_for_testing_member
// ignore_for_file: must_be_immutable
// ignore_for_file: prefer_const_constructors
// ignore_for_file: unnecessary_parenthesis
// ignore_for_file: camel_case_types
// ignore_for_file: subtype_of_sealed_class
// ignore_for_file: invalid_use_of_internal_member

class _FakeNote_0 extends _i1.SmartFake implements _i2.Note {
  _FakeNote_0(
    Object parent,
    Invocation parentInvocation,
  ) : super(
          parent,
          parentInvocation,
        );
}

/// A class which mocks [NotesRepository].
///
/// See the documentation for Mockito's code generation for more information.
class MockNotesRepository extends _i1.Mock implements _i3.NotesRepository {
  MockNotesRepository() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i4.Future<List<_i2.Note>> getNotes() => (super.noSuchMethod(
        Invocation.method(
          #getNotes,
          [],
        ),
        returnValue: _i4.Future<List<_i2.Note>>.value(<_i2.Note>[]),
      ) as _i4.Future<List<_i2.Note>>);

  @override
  _i4.Future<_i2.Note?> getNoteById(String? id) => (super.noSuchMethod(
        Invocation.method(
          #getNoteById,
          [id],
        ),
        returnValue: _i4.Future<_i2.Note?>.value(),
      ) as _i4.Future<_i2.Note?>);

  @override
  _i4.Future<_i2.Note> createNote({
    required String? title,
    required String? body,
    List<String>? tags = const [],
  }) =>
      (super.noSuchMethod(
        Invocation.method(
          #createNote,
          [],
          {
            #title: title,
            #body: body,
            #tags: tags,
          },
        ),
        returnValue: _i4.Future<_i2.Note>.value(_FakeNote_0(
          this,
          Invocation.method(
            #createNote,
            [],
            {
              #title: title,
              #body: body,
              #tags: tags,
            },
          ),
        )),
      ) as _i4.Future<_i2.Note>);

  @override
  _i4.Future<_i2.Note> updateNote(_i2.Note? note) => (super.noSuchMethod(
        Invocation.method(
          #updateNote,
          [note],
        ),
        returnValue: _i4.Future<_i2.Note>.value(_FakeNote_0(
          this,
          Invocation.method(
            #updateNote,
            [note],
          ),
        )),
      ) as _i4.Future<_i2.Note>);

  @override
  _i4.Future<void> deleteNote(String? id) => (super.noSuchMethod(
        Invocation.method(
          #deleteNote,
          [id],
        ),
        returnValue: _i4.Future<void>.value(),
        returnValueForMissingStub: _i4.Future<void>.value(),
      ) as _i4.Future<void>);

  @override
  _i4.Future<List<_i2.Note>> searchByTitle(String? query) =>
      (super.noSuchMethod(
        Invocation.method(
          #searchByTitle,
          [query],
        ),
        returnValue: _i4.Future<List<_i2.Note>>.value(<_i2.Note>[]),
      ) as _i4.Future<List<_i2.Note>>);

  @override
  _i4.Future<List<_i2.Note>> filterByTag(String? tag) => (super.noSuchMethod(
        Invocation.method(
          #filterByTag,
          [tag],
        ),
        returnValue: _i4.Future<List<_i2.Note>>.value(<_i2.Note>[]),
      ) as _i4.Future<List<_i2.Note>>);
}
